import { useState } from 'react'
import { AlertTriangle, BookOpen, Check, Copy, Zap } from 'lucide-react'
import { IconButton, PageHeader, Surface } from '../components/ui'

function Tool({ name, desc, delay }: { name: string; desc: string; delay: string }) { return <div style={{ animationDelay: delay }} className="animate-item rounded-lg bg-slate-50 p-3 transition-all duration-200 hover:translate-x-1 hover:bg-slate-100"><code className="text-xs font-bold text-clio-700">{name}</code><p className="mt-1 text-[11px] text-slate-400">{desc}</p></div> }

export function McpPage() {
  const [copied, setCopied] = useState(false)
  const command = 'MCP 서버 패키지와 API 키 발급 API 구현 필요'
  const copy = () => { navigator.clipboard?.writeText(command); setCopied(true); setTimeout(() => setCopied(false), 1600) }
  return <div className="animate-page"><PageHeader eyebrow="DEVELOPER TOOLS" title="MCP 연동" description="MCP 서버 구현 상태와 예정된 도구를 확인합니다." /><div className="mx-auto max-w-5xl p-5 lg:p-8"><section className="overflow-hidden rounded-2xl bg-slate-950 p-8 text-white"><span className="inline-flex items-center gap-2 rounded-full bg-blue-500/15 px-3 py-1 text-xs font-bold text-blue-300"><Zap size={13} /> Model Context Protocol</span><h2 className="mt-5 text-2xl font-extrabold">Clio 이슈 컨텍스트 연동</h2><p className="mt-3 text-sm text-slate-400">서버에 MCP API 키 발급·조회·재발급 엔드포인트가 아직 없습니다.</p></section><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_280px]"><Surface className="p-7"><div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-5"><AlertTriangle size={19} className="shrink-0 text-amber-600" /><div><h3 className="text-sm font-bold text-amber-800">현재 연결할 수 없습니다.</h3><p className="mt-2 text-xs leading-5 text-amber-700">화면에 있던 설치 명령과 발급 완료 표시는 실제 서버 계약이 아니므로 제거했습니다. MCP 서버 패키지와 API 키 관리 API가 구현되어야 합니다.</p></div></div><div className="mt-5 flex items-center rounded-lg bg-slate-950 px-4 py-3 text-slate-400"><code className="flex-1 text-xs">{command}</code><IconButton onClick={copy}>{copied ? <Check size={15} /> : <Copy size={15} />}</IconButton></div></Surface><Surface className="p-5"><div className="flex items-center gap-2 font-bold text-slate-800"><BookOpen size={17} /> 예정 도구</div><div className="mt-4 space-y-3"><Tool name="list_issues" desc="우선순위 이슈 조회" delay="0ms" /><Tool name="get_issue" desc="이슈 상세 컨텍스트" delay="0ms" /><Tool name="update_issue" desc="작업 상태 업데이트" delay="0ms" /></div></Surface></div></div></div>
}
